version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rfid-backend-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13xtti8er3wuy"
s3_prefix = "rfid-backend-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Env=dev"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "rfid-backend-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13xtti8er3wuy"
s3_prefix = "rfid-backend-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Env=prod"
